name: Automatisation des tests

on: 
  push

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compilation du projet
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Lancer les tests CMake
        run: |
          cd build
          ctest --output-on-failure

  Test_add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test fonction add
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator add 10 5

  Test_sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test fonction sub
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator sub 3 -2

  Test_mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test fonction mul
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator mul 5 5  

  Test_div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test fonction div
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator div 1 5  

  Test_square:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test fonction square
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator square 5
